name: 'home-server'

networks:
  proxy-net:
    name: proxy-net
    driver: bridge
  services-net:
    name: services-net
    internal: false # Needs internet for updates/downloads, but not exposed to host

include:
  - path: reverse-proxy/docker-compose.yaml
  - path: network/docker-compose.yaml
  - path: media/docker-compose.yaml
  - path: home-assistant/docker-compose.yaml
  - path: dashboard/docker-compose.yaml
  - path: octoprint/docker-compose.yaml
