server {
    listen 80;
    server_name pihole.lan;

    location / {
        proxy_pass http://pihole;
        proxy_set_header Host $host;
        proxy_set_header X-Real-IP $remote_addr;
    }
}

server {
    listen 80;
    server_name torrent.local;

    location / {
        proxy_pass http://torrent:8080;
        proxy_set_header Host $host;
        proxy_set_header X-Real-IP $remote_addr;
    }
}