server {
    listen 80;
    server_name pihole;

    location / {
        proxy_pass http://pihole;
        proxy_set_header Host $host;
        proxy_set_header X-Real-IP $remote_addr;
    }
}

server {
    listen 80;
    server_name torrent;

    location / {
        proxy_pass http://torrent:8080;
        proxy_set_header Host $host;
        proxy_set_header X-Real-IP $remote_addr;
    }
}

server {
    listen 80;
    server_name portainer;

    location / {
        proxy_pass http://portainer:9000;
        proxy_set_header Host $host;
        proxy_set_header X-Real-IP $remote_addr;
    }
}


server {
    listen 80;
    server_name speedtest;

    location / {
        proxy_pass http://speedtest;
        proxy_set_header Host $host;
        proxy_set_header X-Real-IP $remote_addr;
    }
}

server {
    listen 80;
    server_name organizr;

    location / {
        proxy_pass http://organizr;
        proxy_set_header Host $host;
        proxy_set_header X-Real-IP $remote_addr;
    }
}
 
server {
    listen 80;
    server_name octoprint;

    location / {
        proxy_pass http://octoprint;
        proxy_set_header Host $host;
        proxy_set_header X-Real-IP $remote_addr;
    }
}

server {
    listen 80;
    server_name jackett;

    location / {
        proxy_pass http://jackett:9117;
        proxy_set_header Host $host;
        proxy_set_header X-Real-IP $remote_addr;
    }
}
 
server {
    listen 80;
    server_name legendas;

    location / {
        proxy_pass http://bazarr:6767;
        proxy_set_header Host $host;
        proxy_set_header X-Real-IP $remote_addr;
    }
}

server {
    listen 80;
    server_name indexas;

    location / {
        proxy_pass http://prowlarr:9696;
        proxy_set_header Host $host;
        proxy_set_header X-Real-IP $remote_addr;
    }
}

server {
    listen 80;
    server_name filmes;

    location / {
        proxy_pass http://radarr:7878;
        proxy_set_header Host $host;
        proxy_set_header X-Real-IP $remote_addr;
    }
}

server {
    listen 80;
    server_name series;

    location / {
        proxy_pass http://sonarr:8989;
        proxy_set_header Host $host;
        proxy_set_header X-Real-IP $remote_addr;
    }
}