# Global Proxy Settings
proxy_set_header Host $host;
proxy_set_header X-Real-IP $remote_addr;
proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
proxy_set_header X-Forwarded-Proto $scheme;

# Homarr Dashboard (Default)
server {
    listen 80;
    server_name dashboard.local "";

    location / {
        proxy_pass http://homarr:7575;
    }
}

# Network Services
server {
    listen 80;
    server_name pihole.local;

    location / {
        proxy_pass http://pihole;
    }
}

# # Media Services
# server {
#     listen 80;
#     server_name torrent.local;
#
#     location / {
#         proxy_pass http://torrent:8080;
#     }
# }
#
# server {
#     listen 80;
#     server_name jackett.local;
#
#     location / {
#         proxy_pass http://jackett:9117;
#     }
# }
#
# server {
#     listen 80;
#     server_name legendas.local;
#
#     location / {
#         proxy_pass http://bazarr:6767;
#     }
# }
#
# server {
#     listen 80;
#     server_name indexas.local;
#
#     location / {
#         proxy_pass http://prowlarr:9696;
#     }
# }
#
# server {
#     listen 80;
#     server_name filmes.local;
#
#     location / {
#         proxy_pass http://radarr:7878;
#     }
# }
#
# server {
#     listen 80;
#     server_name series.local;
#
#     location / {
#         proxy_pass http://sonarr:8989;
#     }
# }

# Utility Services
server {
    listen 80;
    server_name speedtest.local;

    location / {
        proxy_pass http://speedtest;
    }
}

# Octoprint
server {
    listen 80;
    server_name octoprint.local;

    location / {
        proxy_pass http://octoprint;
    }
}
