services:
  octoprint:
    image: octoprint/octoprint
    hostname: octoprint
    container_name: octoprint
    restart: unless-stopped
    devices:
      - /dev/ttyUSB0:/dev/ttyACM0
      - /dev/video0:/dev/video0
    volumes:
      - ${OCTOPRINT_CONFIG}:/octoprint
    environment:
      - ENABLE_MJPG_STREAMER=true
      - TZ=${TIMEZONE}
    networks:
      - services-net
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost"]
      interval: 30s
      timeout: 10s
      retries: 3
