services:
  octoprint:
    image: octoprint/octoprint:1.11.8
    hostname: octoprint
    container_name: octoprint
    restart: unless-stopped
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "3"
    deploy:
      resources:
        limits:
          cpus: '1.0'
          memory: 1G
    devices:
      - /dev/ttyUSB0:/dev/ttyACM0
      # - /dev/video0:/dev/video0
    volumes:
      - ${OCTOPRINT_DATA}:/octoprint
    environment:
      - ENABLE_MJPG_STREAMER=true
      - TZ=${TIMEZONE}
    networks:
      - services-net
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost"]
      interval: 30s
      timeout: 10s
      retries: 3
