services:
  paperless-redis:
    image: redis:${REDIS_VER}
    container_name: paperless-redis
    restart: unless-stopped
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "3"
    deploy:
      resources:
        limits:
          cpus: '0.25'
          memory: 256M
    volumes:
      - ${BASE_DATA_DIR}/paperless/redis:/data
    networks:
      - services-net
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 30s
      timeout: 10s
      retries: 3

  gotenberg:
    image: docker.io/gotenberg/gotenberg:${GOTENBERG_VER}
    container_name: gotenberg
    restart: unless-stopped
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "3"
    deploy:
      resources:
        limits:
          cpus: '0.50'
          memory: 512M
    command:
      - "gotenberg"
      - "--chromium-disable-javascript=true"
      - "--chromium-allow-list=file:///tmp/.*"
    networks:
      - services-net
    healthcheck:
      test: ["CMD", "curl", "-f", "http://127.0.0.1:3000/health"]
      interval: 30s
      timeout: 10s
      retries: 3

  tika:
    image: docker.io/apache/tika:${TIKA_VER}
    container_name: tika
    restart: unless-stopped
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "3"
    deploy:
      resources:
        limits:
          cpus: '0.50'
          memory: 512M
    networks:
      - services-net
    # healhcheck:
    #   test: ["CMD", "curl", "-f", "http://127.0.0.1:9998/"]
    #   interval: 30s
    #   timeout: 10s
    #   retries: 3

  paperless:
    image: ghcr.io/paperless-ngx/paperless-ngx:${PAPERLESS_VER}
    container_name: paperless
    restart: unless-stopped
    depends_on:
      paperless-redis:
        condition: service_healthy
      gotenberg:
        condition: service_healthy
      # tika:
      #   condition: service_healthy
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "3"
    deploy:
      resources:
        limits:
          cpus: '3.0'
          memory: 2G
    environment:
      - PAPERLESS_REDIS=redis://paperless-redis:6379
      - PAPERLESS_TIKA_ENABLED=1
      - PAPERLESS_TIKA_GOTENBERG_ENDPOINT=http://gotenberg:3000
      - PAPERLESS_TIKA_ENDPOINT=http://tika:9998
      - PAPERLESS_TIME_ZONE=${TIMEZONE}
      - PAPERLESS_OCR_LANGUAGE=${PAPERLESS_OCR_LANGUAGE}
      - PAPERLESS_OCR_LANGUAGES=${PAPERLESS_OCR_LANGUAGE}
      - USERMAP_UID=${PUID}
      - USERMAP_GID=${PGID}
      - PAPERLESS_URL=http://paperless.home
      - PAPERLESS_TASK_WORKERS=${PAPERLESS_TASK_WORKERS}
      - PAPERLESS_THREADS_PER_WORKER=${PAPERLESS_THREADS_PER_WORKER}
    volumes:
      - ${BASE_DATA_DIR}/paperless/data:/usr/src/paperless/data
      - ${BASE_DATA_DIR}/paperless/media:/usr/src/paperless/media
      - ${BASE_DATA_DIR}/paperless/export:/usr/src/paperless/export
      - ${BASE_DATA_DIR}/paperless/consume:/usr/src/paperless/consume
    networks:
      - services-net
    healthcheck:
      test: ["CMD", "curl", "-f", "http://127.0.0.1:8000"]
      interval: 30s
      timeout: 10s
      retries: 3
