services:
  homeassistant:
    container_name: homeassistant
    image: ghcr.io/home-assistant/home-assistant:${HA_VER}
    restart: unless-stopped
    cap_add:
      - NET_ADMIN
      - NET_RAW
    networks:
      - services-net
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "3"
    deploy:
      resources:
        limits:
          cpus: '1.00'
          memory: 1G
    environment:
      - TZ=${TIMEZONE}
    volumes:
      - ${BASE_DATA_DIR}/homeassistant:/config
      - /etc/localtime:/etc/localtime:ro
      - /run/dbus:/run/dbus:ro
    healthcheck:
      test: ["CMD", "curl", "-f", "http://127.0.0.1:8123"]
      interval: 30s
      timeout: 10s
      retries: 3

  esphome:
    container_name: esphome
    image: ghcr.io/esphome/esphome:${ESPHOME_VER}
    restart: unless-stopped
    networks:
      - services-net
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "3"
    deploy:
      resources:
        limits:
          cpus: '0.75'
          memory: 1G
    environment:
      - ESPHOME_USERNAME=${ESPHOME_USERNAME}
      - ESPHOME_PASSWORD=${ESPHOME_PASSWORD}
      - TZ=${TIMEZONE}
    volumes:
      - ${BASE_DATA_DIR}/esphome:/config
      - /etc/localtime:/etc/localtime:ro
    healthcheck:
      test: ["CMD-SHELL", "curl -f http://127.0.0.1:6052 || exit 1"]
      interval: 30s
      timeout: 10s
      retries: 3
